### ISSUE TITLE
[S1-PB1] Halaman Utama

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#1]
Sebagai user saya ingin mengakses halaman utama agar saya bisa lebih mudah melihat dan mengakses fitur dalam website

![Image](https://user-images.githubusercontent.com/83771164/230816984-871e3243-5d0b-4966-bed4-af59137ec8dc.png)

**Comment by tienfkusumasari** [comment]
tambahakn konten di html

**Comment by tienfkusumasari** [comment]
ambil dari tabel wahan yang diinput admin
