### ISSUE TITLE
[S1-PB20] Database

### ISSUE THREAD

**Issue by fatihabdi** [SI-RPL-2023/SI4401-223-Ritapark#14]
![Image](https://user-images.githubusercontent.com/69069374/230804619-c0f92d8e-145b-49c6-8c63-9b051e86fcd6.png)

![Image](https://user-images.githubusercontent.com/69069374/230804651-7616580b-91f3-4c8a-a00b-50a771dde12f.png)

**Comment by fatihabdi** [comment]
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/69069374/229386455-f1cd857e-c6bf-4296-977f-55019f6340cb.png">

**Comment by fatihabdi** [comment]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/69069374/229386485-e175a7b8-3b0c-4f8e-96b1-5ac17ef69745.png">

**Comment by tienfkusumasari** [comment]
close SP1
