### ISSUE TITLE
[S1-PB5] halaman registrasi

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#2]
Sebagai user saya ingin melakukan registrasi akun baru pada website, agar saya dapat membuat akun pribadi pada website dan memasukan informasi pribadi dengan tepat untuk administrasi dalam aplikasi.  
Tujuan: 
Membuat halaman antarmuka registrasi yang terhubung dengan database yang dapat berfungsi untuk membuat akun baru.

Mockup: 
![Image](https://user-images.githubusercontent.com/71767260/232355484-43f85d90-b2a1-42eb-a4e7-d16bf33ecc90.png)

Alur Registrasi:
Pada halaman registrasi, user dapat melakukan pembuatan, melihat, dan mengedit informasi mengenai akun pribadi mereka.
![Image](https://user-images.githubusercontent.com/71767260/232355663-7b95a8d3-f66e-4953-aa48-b4c900603aa3.png)

**Comment by tienfkusumasari** [comment]
detailkan PBI story nya , tambahkan tujuan, tambah kan mockup, tambahkan alur registrasi . CRU (-penjelasan)
code baru dibuat sampai create saja
