### ISSUE TITLE
[S0-PB21] Membuat Proses Bisnis Eksisting

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#27]
Sebagai admin, saya ingin mengetahui bagaimana proses bisnis yang dimiliki oleh mitra sekarang

![Image](https://user-images.githubusercontent.com/97177161/230808048-ad093b1d-3525-4a73-a5ef-21e2233dd509.png)

Proses Bisnis Feedback dan Rating Eksisting

![Image](https://user-images.githubusercontent.com/83771164/230813463-3df17273-b390-4b59-a619-5560819ccc95.jpg)

**Comment by tienfkusumasari** [comment]
ok
