### ISSUE TITLE
[S0-PB22] Membuat Proses Bisnis Targeting

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#28]
Sebagai admin, saya ingin memperbarui proses bisnis saya agar lebih efisien dan efektif

Proses Bisnis Targeting Feedback dan Rating

![Image](https://user-images.githubusercontent.com/83771164/230814654-2909c4d5-065f-4326-b020-deef1d1224fc.png)

![Image](https://user-images.githubusercontent.com/97177161/230814739-383cf2cf-4ee5-4334-b180-a0f06ef614bc.png)

**Comment by tienfkusumasari** [comment]
ok
