### ISSUE TITLE
[S1-PB13] halaman CRUD Ticket

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#3]
Saya sebagai admin ingin melakukan edit konten agar saya dapat membuat, melihat, mengubah dan menghapus konten sesuai dengan keperluan

**Comment by tienfkusumasari** [comment]
jadikan 2 PBI ==> PBI CRUD (edit dan delete belum jalan) wahana dan PBI CRUD Tiket (close SP1)
