### ISSUE TITLE
[S0-PB25] Membuat Class Diagram

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#30]
Sebagai admin, saya ingin membuat Class Diagram untuk sebuah sistem manajemen website. dengan class diagram sebagai berikut

![Image](https://user-images.githubusercontent.com/69069374/230802542-2cb16250-d4e2-4d7c-8f4f-b22804206a23.png)

**Comment by tienfkusumasari** [comment]
ok
