### ISSUE TITLE
[S0-PB27] Membuat ERD merge ke #14

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#32]
Membuat database dari ERD dengan entitas dan atribut sebagai berikut

![Image](https://user-images.githubusercontent.com/69069374/230802596-fe8d0d28-9bd8-44f3-9559-033ac64b65c8.png)

**Comment by tienfkusumasari** [comment]
merege ke issue #14
