### ISSUE TITLE
[S1-PB14] halaman login

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#4]
Sebagai user saya ingin melakukan login agar saya dapat mengakses dan menggunakan fitur aplikasi secara lengkap dengan menggunakan password dan email address

![Image](https://user-images.githubusercontent.com/97177161/230816565-806ae549-48f5-47a7-9c01-814f90ddaaff.png)

**Comment by tienfkusumasari** [comment]
PBI detailkanbagaimana cara login dan pakai apa, trus tambahkan mockup

**Comment by tienfkusumasari** [comment]
close SP1
