### ISSUE TITLE
[S1-PB15] fitur logout

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#5]
Saya sebagai user dan admin ingin logout agar saya dapat keluar dari website tanpa meninggalkan personalisasi saya saat digunakan oleh pelanggan lain

![Image](https://user-images.githubusercontent.com/97177161/230816648-309e9063-7be8-4cb4-b2d9-e635c416cc3a.png)

**Comment by tienfkusumasari** [comment]
PBI nya kasih mock up

**Comment by tienfkusumasari** [comment]
close SP1
