### ISSUE TITLE
[S3-PB8] halaman profile saya

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#54]
Sebagai pengguna, saya ingin mengubah data akun saya pada website sehingga ketika ada kesalahan data bisa saya perbaiki. Seperti mengubah nama, email, no hp, dan password. Selain itu saya dapat melakukan logout akun saya dari website melalui halaman profile ini.

![Image](https://github.com/SI-RPL-2023/SI4401-223-Ritapark/assets/97177161/453c0e4c-7508-474b-bcc6-d40505f5eab9)
![Image](https://github.com/SI-RPL-2023/SI4401-223-Ritapark/assets/97177161/53609835-2bc4-4242-9bae-3676205f1b1e)
![Image](https://github.com/SI-RPL-2023/SI4401-223-Ritapark/assets/97177161/8eb6e5c9-cb54-4ff4-aba5-71785e8da766)

Tampilan ketika berhasil :

![Image](https://github.com/SI-RPL-2023/SI4401-223-Ritapark/assets/97177161/d1a01e49-4ae2-426d-b09d-794bc81972c9)

Alur :
1. User harus login terlebih dahulu ke akun
2. Pada navbar, klik tombol Akun
3. User akan diberikan informasi mengenai akun mereka seperti nama, username, nomor telpon
4. User menekan tombol "Ubah akun" untuk mengubah detail informasi mereka
5. User menekan huruf "Klik disini untuk ubah password"

Test case, menguji apakah bisa melakukan sesuatu yang bersimpangan dari yang seharusnya. Berikut merupakan list test case yang akan dilakukan :
1. Ubah nomor telpon dengan huruf
2. Ubah nomor telpon secara asal, semisal hanya 5 angka
3. Isi nama panjang dengan angka
4. Ubah password tapi antara password dan konfirmasi berbeda
5. Masukan password hanya 2 karakter

**Comment by tienfkusumasari** [comment]
automatic testing masih nge bug, sempet jalan sebentar
