### ISSUE TITLE
[S3-PB29] Melihat testimoni

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#58]
Sebagai user, saya ingin dapat melihat testimoni dari pengguna lain tentang produk dan layanan yang ditawarkan, sehingga saya bisa mempertimbangkan pengalaman mereka sebelum membuat keputusan pembelian. Hasil testimoni akan di munculkan di halaman utama dan akan dimunculkan 3 terbaru dan data di ambil dari tabel menulis testimoni

User story: Melihat Testimoni di Halaman Utama

Deskripsi: Sebagai pengguna, saya ingin dapat melihat testimoni dari pelanggan lain di halaman utama situs web agar dapat memperoleh pemahaman tentang pengalaman positif yang telah mereka miliki dengan produk atau layanan yang ditawarkan.

1. Pengguna harus log in terlebih dahulu
2. Setelah berhasil log in,  Pengguna dapat melihat daftar testimoni yang ditampilkan dengan jelas di halaman utama situs web.
3. Setiap testimoni  mencakup nama pelanggan, tanggal di publish, rating, dan isi testimoni yang relevan.
4. Testimoni  disajikan secara visual menarik dan mudah dibaca.

Test case, menguji apakah bisa melakukan sesuatu yang bersimpangan dari yang seharusnya. Berikut merupakan list test case yang akan dilakukan :
1. Verifikasi bahwa testimoni menampilkan informasi yang sesuai, seperti nama pengguna, isi testimoni, dan rating.

![Image](https://github.com/SI-RPL-2023/SI4401-223-Ritapark/assets/83771164/bcc8d6ff-341f-471f-97cd-c3581b143873)

**Comment by tienfkusumasari** [comment]
tambahkan utk lihat semua untuk admin

**Comment by tienfkusumasari** [comment]
automatic testing belum jalan

**Comment by tienfkusumasari** [comment]
automatic testing dan list fitur testimoni sudah ada
