### ISSUE TITLE
[S1-PB16] Halaman wahana

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#6]
Saya sebagai user ingin Melihat halaman wahana agar saya dapat mengetahui informasi dan detail dari berbagai wahana yang tersedia di Rita Park
![wahana](https://user-images.githubusercontent.com/115634696/230824747-07f4914f-c118-46c9-a205-dae5ae7156d0.jpeg)

**Comment by tienfkusumasari** [comment]
ambil konten dari DB

**Comment by tienfkusumasari** [comment]
detailkan PBI nya tambah mockup , relasi db ambil dr tabel mana
