### ISSUE TITLE
[S3-PB30] Tambah Promo admin

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#65]
Sebagai admin saya ingin menambah promo pada website sehingga ketika user melakukan pembayaran maka mendapatkan potongan harga.

![Image](https://github.com/SI-RPL-2023/SI4401-223-Ritapark/assets/97177161/b22a979d-d6fe-4a30-a0d5-7bfa4fb2b3e3)
![Image](https://github.com/SI-RPL-2023/SI4401-223-Ritapark/assets/97177161/14e12e56-d04d-4a68-8163-c2e0e4eee48e)

![Image](https://github.com/SI-RPL-2023/SI4401-223-Ritapark/assets/97177161/e9efc4a0-ce81-4749-a151-38ae950af613)
![Image](https://github.com/SI-RPL-2023/SI4401-223-Ritapark/assets/97177161/7f7437a2-b1bf-4405-bd46-0f32273b6690)

![Image](https://github.com/SI-RPL-2023/SI4401-223-Ritapark/assets/97177161/49248d9c-1a37-4a83-a646-cebddb4d2dcf)

Alur :

1. Admin harus login terlebih dahulu ke akun
2. Pada navbar, klik menu promo
3. Admin akan diberikan informasi mengenai promo yang telah ada
4. Admin menekan tombol "tambah promo" untuk menambah promo
5. Admin menekan tombol "ubah" untuk melakukan edit promo
6. Admin menekan tombol "hapus" untuk menghapus promo

Test case, menguji apakah bisa melakukan sesuatu. Berikut merupakan list test case yang akan dilakukan :

1. Melakukan input promo
2. Melakukan edit promo yang sudah ada
3. Melakukan hapus promo
4. Apakah bisa membuat atau edit promo ketika tanggal mulai lebih dari tanggal selesai?
5. Apakah status akan berubah menjadi tidak aktif ketika tanggal mulai lebih dari tanggal sekarang?

**Comment by tienfkusumasari** [comment]
automatic testing belum jalan
