### ISSUE TITLE
[S1-PB18] fitur contact us

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#7]
Sebagai pengguna website, saya ingin dengan mudah menemukan kontak pengaduan jika terjadi kendala melalui whatsapp agar lebih mudah. Tombol akan mengarahkan langsung ke whatsapp dengan nomor telpon yang sudah ditentukan

mekanisme nya adalah tombol akan membuka website https://wa.me/+6281328782510 dengan nomor telpon yang tertera

![Image](https://user-images.githubusercontent.com/97177161/230816285-e01db6a5-ba2c-4bea-a528-dc46b92838c3.png)

![Image](https://user-images.githubusercontent.com/97177161/230816307-d45ddefd-9ebc-4644-8f00-14e0a92ec9f5.png)

![Image](https://user-images.githubusercontent.com/97177161/230817441-4d702bc3-4ccf-42e1-90a6-5b8f4fdbe9ef.png)

**Comment by lintanganugerah** [comment]
Fitur contact us sudah dapat berjalan. Fitur dapat digunakan di setiap halaman dengan melakukan include

**Comment by tienfkusumasari** [comment]
penulisan story di detial kan

**Comment by tienfkusumasari** [comment]
tambahkan mockup dan probis serta mekanisme konek ke wa nya

**Comment by tienfkusumasari** [comment]
tambahkan mockup dan probis serta mekanisme konek ke wa nya

**Comment by tienfkusumasari** [comment]
close SP1
