### ISSUE TITLE
[S1-PB3] Halaman beli tiket

### ISSUE THREAD

**Issue by lintanganugerah** [SI-RPL-2023/SI4401-223-Ritapark#8]
Saya sebagai user ingin melakukan beli tiket agar saya dapat memesan tiket masuk tanpa perlu datang langsung ke lokasi taman bermain
![dasdasd](https://user-images.githubusercontent.com/126361688/232361611-8efc3691-839b-4d34-9d49-fa6a73149ff3.PNG)
![beli](https://user-images.githubusercontent.com/126361688/232361623-dde0fa27-47b6-4308-a553-fe5f91d2d409.PNG)

**Comment by tienfkusumasari** [comment]
tambahkan mockup, kasih alur probis beli tiket. belum ditangai setelah di input pembelian dan belum masuk ke DB
